config/routes.rb
Adsitape::Application.routes.draw do
  get "videos/show"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  match '/auth/facebook/logout' => 'application#facebook_logout', :as => :facebook_logout

  get "pages/home"
  get "pages/historico"
  get "pages/contribua"
  get "pages/cronograma"
  get "pages/tutoriais"
  get "pages/infraestrutura"
  get "pages/sobre"
  get "pages/contato"
  get "cronograma/basico"

  root :to => "pages#home"

  match '/home',          :to => 'pages#home'
  match '/historico',     :to => 'pages#historico'
  match '/contribua',     :to => 'pages#contribua'
  match '/cronograma',    :to => 'pages#cronograma'
  match '/tutoriais',     :to => 'pages#tutoriais'
  match '/infraestrutura',:to => 'pages#infraestrutura'
  match '/sobre',         :to => 'pages#sobre'
  match '/contato',       :to => 'pages#contato'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.where(:email => data.email).first
      user
    else # Create a user with a stub password. 
      User.create!(:email => data.email, :password => Devise.friendly_token[0,20]) 
    end
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"]
      end
    end
  end
  
end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def facebook_logout
    session=nil
    @logging_out = true  
    #request.cookies = nil  
    
    #session.warden.user.user.key = ""
    redirect_to root_path
  end
  
  
end

app/controllers/cronograma_controller.rb
class CronogramaController < ApplicationController
  def basico
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    @title = "Home"
  end

  def historico
    @title = "Historico"
  end

  def contribua
    @title = "Contribua"
  end

  def cronograma
    @title = "Cronograma"
  end
  
  def tutoriais
    @title = "Tutoriais, Guias e outros"
  end
  
  def infraestrutura
    @title = "Infra-Estrutura"
  end

  def sobre
    @title = "Sobre AdsItape.com"
  end
  
  def contato
    @title = "Contato"
  end  

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def show
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def title
    base_title = "AdsItape.com"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
 
end

app/helpers/cronograma_helper.rb
module CronogramaHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def topo_adsitape
      if !(@title.nil?) && !(@title == 'Home')
        raw("<h1> adsitape.com </h1>
              <hr />
              <h2> #{@title} </h2>")
      end
  end 
  
  def helper_logo_infra(name, imagem, texto_alt, endereco, texto_link)
    imagem = "infraestrutura/#{imagem}"
    name = image_tag(imagem, 
                    :alt => texto_alt,
                    :class => 'logo_infra')
    link_imagem = link_to name, endereco
    link_texto = link_to texto_link, endereco
    
    raw("#{link_imagem} <br> #{link_texto}")
  end
  
  def helper_imagem_historico(arquivo)
    imagem = "historico/#{arquivo}"
    texto = image_tag(imagem, :alt => arquivo,
                              :class => 'img_historico')
    raw(texto)
  end
  
  def helper_tutorial(titulo, descricao, autor, data,
                      versao1, arquivo1, tamanho1,
                      versao2, arquivo2, tamanho2)
    arquivo1 = "tutoriais/#{arquivo1}"
    link1 = link_to versao1, arquivo1
    link1 = "#{link1}, #{tamanho1}"
    
    arquivo2 = "tutoriais/#{arquivo2}"
    link2 = link_to versao2, arquivo2
    link2 = "#{link2}, #{tamanho2}"
  
    raw("<table class=\"tab_tutorial\">
            <tr>
                <td class=\"tutorial\">
                    #{titulo}<br />
                    #{descricao}
                </td>
            </tr>
            <tr>
                <td>
                    Autor: #{autor}, publicado em #{data},
                    versão #{link1}, versão #{link2} 
                </td>
            </tr>
        </table>
        ")
  end
end

app/helpers/users_helper.rb
module UsersHelper

require 'timeout'
require 'socket'  
    
  def facebook_acessivel?
      if Rails.env.production?
        begin
          Timeout.timeout(5) do 
            s = TCPSocket.new('www.facebook.com', 'echo')
            s.close
            return true
          end
          rescue Errno::ECONNREFUSED
            return true
          rescue Timeout::Error
            return false
        end
      else 
         true
      end
  end
  
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/cronograma/basico.html.erb
	<header>
		
		<p class="pcenter">mande sugestões: <a href="mailto:luiz.jesus@fatec.sp.gov.br">
			luiz.jesus@fatec.sp.gov.br</a>
		</p>
	</header>
  	<div class="emconstrucao">
  		<% logo = image_tag("sem_logo.gif", :alt => "Alguém pode criar um logo pra pôr aqui?", :class => "logotipo")%>
  		<%= link_to logo, root_path %>
  		<h1>AdsItape.com</h1>
  		<h1>Este site está em Construção</h1>
  			<p class="pcenter"><i>Só para o caso de você não ter percebido...</i></p>
  			<h2>Proposta:</h2>
  				<p>Desenvolver ferramentas de interatividade para os alunos 
  					do curso de Análise e Desenvolvimento de Sistemas
  					da Fatec Itapetininga.<br />
  				   No processo, aprender sobre 
  				  <a href="http://rubyonrails.org">Ruby on Rails</a>
  				   e o que mais aparecer pelo caminho.	
  				</p>
  			<hr />
  	</div>
  	<div class="conteudo">
  	<h2>Solicitação de Ajuda</h2>
  		<table>
  			<tr>
  				<td>Logotipo</td>
  				<td>preciso de um logotipo para o site. 
  					Você pode criar um (imagem em formato .gif ou .jpg) e me mandar por e-mail</td>
  			</tr>
  			<tr>
  				<td>Estilização</td>
  				<td>Que tal brincar com CSS e me ajudar a criar um bom estilo para este site?
  					No seu navegador, clique Arquivo/ Salvar Como (ou algo parecido),
  					salve esta página em uma pasta no seu computador.<br />
  					Abra a pasta e dê clique duplo no arquivo index.html para ele abrir no seu navegador<br />
  					Volte para a pasta, deve ter um subpasta adsitape_files (ou algo parecido), dentro dela
  					deve ter um arquivo <b>custom.css</b><br />
  					Abra esse arquivo com o bloco de notas, altere alguma coisa (um item de cada vez!),
  					salve o arquivo, volte para o navegador e pressione F5 para ver o que mudou.<br />
  					Quando achar que terminou, me mande o seu arquivo css por e-mail!<br />
  					</td>
  			</tr>  			
  		</table>
  	<h2>Cronograma</h2>
  		<table>
  			<tr>
  				<td>Página de aviso de construção</td>
  				<td>05/12/2011</td>
  			</tr>
  			<tr>
  				<td>Estilização de página de aviso e rascunho do logotipo</td>
  				<td>06/12/2011</td>
  			</tr> 
  			<tr>
  				<td>Colocar a primeira página no ar (para o mundo!)<br />
  					A empresa onde pretendia hospedar o site não suporta Rails 3.1<br />
  					Então por enquanto vai html puro mesmo, até achar outra solução pra isso
  					</td>
  				<td>07/12/2011</td>
  			</tr>   			 			
  			<tr>
  				<td>Tutorial para criação de ambiente para desenvolvimento Ruby on Rails<br />
  					(Ubuntu 11.10, Ruby 1.9.2, Rails 3.1, Aptana IDE, PostgreSql)</td>
  				<td>15/12/2011</td>
  			</tr>
  			<tr>
  				<td>Melhoramento Visual e Funcional (menus, estilização)</td>
  				<td>20/12/2011</td>
  			</tr>
  			<tr>
  				<td>Em Férias a partir de 23/12 (sem internet nem celular)</td>
  				<td>02/01/2012</td>
  			</tr>
  			<tr>
  				<td>Adaptação em Português do Ruby on Rails Tutorial de Michael Hartl</td>
  				<td>03/02/2012</td>
  			</tr>
  			<tr>
  				<td colspan="2">
  					<p>Depois começam as aulas, aí qualquer previsão é impossível</p>
  				</td>
  			</tr>  			
  		</table>
  	</div>

app/views/layouts/_footer.html.erb
		<footer>
  			<nav class="round">
  				<hr>
          		<ul>
           	 		<li><%= link_to "Infra-Estrutura", 	infraestrutura_path %></li>
            		<li><%= link_to "Sobre", 			sobre_path %></li>
            		<li><%= link_to "Contato", 			contato_path %></li>            		
          		</ul>
          		<%= render "layouts/facebook/botaocurtir"%>
        	</nav>			
		</footer>
		

app/views/layouts/_header.html.erb
		<header>
			<% logo = image_tag("sem_logo.gif", :alt => "Alguém pode criar um logo pra pôr aqui?", :class => "logotipo round")%>
  			<%= link_to logo, contribua_path %>
  			
         	<nav class="round">
          		<ul> 			
           	 		<li><%= link_to "Home", 		root_path %></li>
            		<li><%= link_to "Contribua", 	contribua_path %></li>
            		<li><%= link_to "Histórico", 	historico_path %></li>            		
            		<li><%= link_to "Cronograma", 	cronograma_path %></li>
            		<li><%= link_to "Tutoriais", 	tutoriais_path %></li>
				</ul>
				<hr>
				
          		<ul>
          		
          			<% if @logging_out %>
          				<p>logging out </p>
          				<% session.warden.user.user.key = "" %>
          			<% end %>
          		

        	     <% if !user_signed_in? %>

						<li>não entrou ainda! <br><%= link_to "Entrar via Facebook", user_omniauth_authorize_path(:facebook) %></li>

					<li>login manual: <%= render "layouts/facebook/login_manual" %></li>
				<% else %>
					<li>Usuário: <%= current_user.email %> <br />
						<%= link_to "Sair", facebook_logout_path %>
					</li>
				<% end %>
				
					
					
          		</ul>	
          		<hr>			
        	</nav>
        	
		</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'nav', :media => 'screen' %>

app/views/layouts/application.html.erb
    <% if Rails.env.development? %>
    <% @facebook_id =  "308830389185988" %>
    <% @facebook_secret = "eb00a37ffea22c5ec66ba5805e12aaa7" %>
  <% else %>
    <% if Rails.env.production? %>
      <% @facebook_id =  "256502224413686" %>
      <% @facebook_secret = "f0cf4fa2da48ad874325b43d686b760c" %>
    <% end %>
  <% end %>

<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <meta name="author" content="Luiz Soares de Jesus" />
  <meta name="keywords" content="rails, ruby on rails, desenvolvimento, tutoriais, fatec, itapetininga" />
  <meta name="description" content="desenvolvimento de projetos ruby on rails" />
  <meta http-equiv="content-language" content="pt-br" />
  <meta http-equiv="content-type" content="application/xhtml+xml; charset=iso-8859-1" />
  <meta name="reply-to" content="luiz.jesus@fatec.sp.gov.br" />
  <meta property="fb:admins" content="100003033741161" />
  
  
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets' %>
</head>
<body>
		<%= render "layouts/facebook/load_sdk"%>
	
		<div class="container round">
			<%= render 'layouts/header' %>
			
				<div class="conteudo">
				<%= topo_adsitape %>
				
				<%= yield %>
				</div>
			
			<%= render 'layouts/footer' %>
			
			<%= render "layouts/facebook/caixacomentarios"%>
			
			<% if Rails.env.development? %>
			  	<%= debug(params) %>
			  	<% session.each do |key, value| %>
          			<p> <%= key %>: <%= value %></p>
        		<% end %>
        		
        		
			<% end %>
		</div>
</body>
</html>

app/views/layouts/facebook/_botaocurtir.html.erb
<div class="fb-like" data-href="http://www.adsitape.com" data-send="false" data-width="450" data-show-faces="true" data-font="segoe ui"></div>		

app/views/layouts/facebook/_caixacomentarios.html.erb
<div class="fb-comments" data-href="<%= request.url %>" data-num-posts="3" data-width="700"></div>

app/views/layouts/facebook/_load_sdk.html.erb
      <div id="fb-root"></div>
		<script>
			(function(d, s, id) 
				{
				  var js, fjs = d.getElementsByTagName(s)[0];
				  if (d.getElementById(id)) return;
				  js = d.createElement(s); js.id = id;
				  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=<%=@facebook_id%>";
				  fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk')
			);
		</script>

app/views/layouts/facebook/_login_manual.html.erb
<form name=login_manual>
	Aqui vai um formulário de login manual
</form>

app/views/layouts/facebook/_test_user.html.erb
<p>
		<% if user_signed_in? %>
			usuário logado! ( <%= current_user.email %> )</p>
		<% else %>
			não entrou ainda! <%= link_to "Entrar via Facebook", user_omniauth_authorize_path(:facebook) %></p>
		<% end %>
<% if (!flash.nil?) && (flash.count >= 1) %>		
		<% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
<% end %>   
  
<% if (!notice.nil?) %>	   
		<% notice.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>        
<% end %>

app/views/pages/_login_ou_registro.html.erb
//		<p>
	<%= link_to "login", '#', :class => "signup_button round" %>
	ou
		<%= link_to "registre-se", '#', :class => "signup_button round" %>
		</p>

app/views/pages/android/videos/videos01.html.erb
<p> Página Stub </p>

app/views/pages/contato.html.erb
<% foto = image_tag("luizsoares.jpg", :alt => "Luiz Soares de Jesus",
						:class => "foto", 
						:width => 120, :height => 150)%>
  			<%= link_to foto, 'http://www.facebook.com/profile.php?id=100003033741161' %>
<p>Luiz Soares de Jesus</p>
<p>é o idealizador deste site</p>
	<ul>
		<li><%= link_to "luiz.jesus@fatec.sp.gov.br", 
								'mailto:luiz.jesus@fatec.sp.gov.br', 
								:class => "signup_button round" %>
								</li>
		<li><%= link_to "facebook", 
								'http://www.facebook.com/profile.php?id=100003033741161', 
								:class => "signup_button round" %>
			
								</li>
		<li><%= link_to "LinkedIn", 
								'http://www.linkedin.com/profile/view?id=146387300&trk=tab_pro', 
								:class => "signup_button round" %>
			  				</li>
		<li>3o. semestre do curso de Análise e Desenvolvimento de Sistemas,<br> 
				   na <%= link_to "Fatec Itapetininga - Prof. Antônio Belizandro Barbosa Rezende", 
								'http://www.fatecitapetininga.edu.br/site2/', 
								:class => "signup_button round" %>
								</li>
		<li>desde maio/2006, 
			Gerente de TI na 
					  <%= link_to "Sabrina Jóias", 
								'http://www.sabrinajoias.com.br', 
								:class => "signup_button round" %>
								</li>
		<li>mora em 
					  <%= link_to "Cesário Lange, SP, Brasil", 
								'http://facebook.com/CesarioLange', 
								:class => "signup_button round" %> 
								</li>
		<li>
			Em breve está página terá um formulário para envio de críticas, sugestões, etc.
			Este recurso estará disponível assim que eu aprender a construí-lo.
		</li>
	</ul>
<hr />
<h2>Colaboradores</h2>
	<ul>
		<%= link_to "seja um!", 
								contribua_path, 
								:class => "signup_button round" %>
	</ul>
	

app/views/pages/contribua.html.erb
<p>Faça parte deste projeto! 
	Toda ajuda é bem-vinda, principalmente quanto à parte de design. 
	O que é oferecido em troca: uma referência na página de 
		<%= link_to 'contato', contato_path %>.</p>
<p>Qualquer contribuição pode ser enviada por 
		<%= link_to 'e-mail para luiz.jesus@fatec.sp.gov.br',
					'mailto:luiz.jesus@fatec.sp.gov.br' %>			
<hr />
<table>
	<tr>
		<td>
			Logotipo
		</td>
		<td>
			Uma imagem para ser usada como logotipo para este site?
			Realmente não consigo ter uma boa idéia para isto.
			Você pode construir uma.
		</td>
	</tr>
	<tr>
		<td>
			Estilização
		</td>
		<td>
			Um CSS melhor?
			Você pode salvar esta página no seu computador e
			editar o arquivo "custom.css", e me mandar sua
			sugestão de versão melhorada para ele.
		</td>
	</tr>
</table>
			
		

app/views/pages/cronograma.html.erb
<p>Em um futuro próximo, isto deverá ser preenchido pelo Rails
	a partir de uma tabela no banco de dados.
	Por enquanto, vai html estático mesmo.</p>
<h3>Atividades em Desenvolvimento (e a serem desenvolvidas)</h3>	
<hr />
<table>

	<tr>
		<td>Projetar e escrever o sistema de interatividade para alunos/turmas da Fatec,
			incluindo estudar a API do Facebook para login de usuários
			
		</td>
		<td>06 a 08/04/2012 
		</td>
	</tr>
	
	<tr>
		<td>Com logins funcionando, publicar vídeos de treinamento Android<br>
			desenvolver sistema de fórum para o Grupo de Android
		</td>
		<td>08/04/2012 a 15/04/2012
		</td>
	</tr>	
		
</table>

app/views/pages/historico.html.erb
<p>Em um futuro próximo, isto deverá ser preenchido pelo Rails
	a partir de uma tabela no banco de dados.
	Por enquanto, vai html estático mesmo.</p>
<hr />
<table>

	<tr>
		<td>20/12/2011</td>
		<td>Versão 0.51 publicada<br>
			Teste de alteração no CSS para tons amarelos + alteração da fonte padrão.
		</td>
		<td><%= helper_imagem_historico('versao_051.png') %></td>
	</tr>

	<tr>
		<td>20/12/2011</td>
		<td>Versão 0.50 publicada<br>
			Com os dois primeiros tutoriais. (ufa!)
		</td>
		<td><%= helper_imagem_historico('versao_050.png') %></td>
	</tr>

	<tr>
		<td>16 a 19/12/2011</td>
		<td>Versão 0.50 em desenvolvimento<br>
			distribuição de conteúdos por páginas,
			com menu superior e inferior,
			padronização da estilização CSS
			( <%= link_to 'ainda preciso de um melhor', contribua_path %> ),
			layout final para os dois primeiros tutoriais
		</td>
		<td></td>
	</tr>

	<tr>
		<td>14/12/2011</td>
		<td>Versão 0.10<br />
			Agora rodando no Cloud Server,
			veja a página de <%= link_to 'Infra_Estrutura', infraestrutura_path %>
		</td>
		<td><%= helper_imagem_historico('versao_010.png') %></td>
	</tr>

	<tr>
		<td>08/12/2011</td>
		<td>Cloud Server Locaweb contratado
		</td>
		<td></td>
	</tr>
	
	<tr>
		<td>07/12/2011</td>
		<td>Versão 0.10 publicada<br>
			single-page de html puro, 
			em uma hospedagem compartilhada da Locaweb
		</td>
		<td><%= helper_imagem_historico('versao_010.png') %></td>
	</tr>

	<tr>
		<td>06/12/2011</td>
		<td>Versão 0.01, tentativa sem sucesso de publicação<br>
			não consegui rodar o Rails 3.1.3 na hospedagem compartilhada 
			da Locaweb. Quase certeza que a falha era minha
			e não deles, mas desisti de qualquer forma.
		</td>
		<td></td>
	</tr>
		
</table>

app/views/pages/home.html.erb
	<h1>ADSITAPE.COM</h1>
		<p>desenvolvendo função de login via facebook....</p>
	<h2>Proposta</h2>
		<p>Explorar o framework Ruby on Rails;</p>
		<p>Estudar desenvolvimento para Android,
				com o <%= link_to 'Grupo de Estudos para Android da Fatec Itapetininga', 'https://www.facebook.com/groups/326762957380602/'%>
			;</p>
		<p>Desenvolver ferramentas de interatividade para os alunos da Fatec Itapetininga;</p>
		<p>Disponibilizar conteúdo voltado à área de Desenvolvimento de Sistemas em geral.</p>
		<p>&nbsp;</p>
	<hr />
	<h2>Este Site está em construção! (permanentemente) </h2>
		<p>Este é um projeto para estudos.
			Conteúdos e ferramentas podem ser eliminados ou acrescentados,
				no decorrer do desenvolvimento.
				Eventualmente, alguns deles não funcionarão como esperado,
				(nesse caso, espero que você me avise,
				e me ajude na solução).
			Só pra começar, você pode sugerir um CSS novo...</p>		
		<p>&nbsp;</p>
		<p>&nbsp;</p>

	<h3>Aviso de Responsabilidade</h3>
		<p>Este projeto é destinado aos alunos da Fatec de Itapetininga,
				mas sua publicação é de responsabilidade do autor 
				(e eventuais colaboradores, quando mencionados). 
				Nenhuma responsabilidade sobre o conteúdo será atribuída à Diretoria, 
				corpo docente 
				ou funcionários da referida Instituição.</p>
		

app/views/pages/sobre.html.erb
<h3>Origem</h3>
	<p>Este projeto nasceu com o objetivo de estudar o framework RubyOnRails.</p>
	<p>Acontece que sou um péssimo estudante, não consigo aprender algo apenas examinando a teoria,
			preciso de um objetivo real, onde possa enfrentar problemas reais
			e me sentir obrigado a correr atrás das soluções.<br>
		Provavelmente este é um dos motivos que me levaram a entrar 
			no mundo de desenvolvimento de software:
			o desafio de problemas novos todos os dias,
			para os quais existe um solução que pode ser desconhecida,
			mas pode ser alcançada ou encontrada de alguma forma. 
		</p>
		
<h3>Proposta</h3>
	<ul>
		<li>Desenvolver uma aplicação RubyOnRails, explorando o máximo de recursos do framework. 
			Gradativamente, disponibilizar:
		</li>
		<ul>
			<li>área de tutoriais e guias para download, cobrindo os desafios enfrentados;
			</li>
				<ul>
					<li>permitir a publicação também por usuários cadastrados;
					</li>
				</ul>
			<li>área de estudo de algoritmos, 
					comparando a solução para o mesmo problema lógico em diversas linguagens
					(pascal, java, ruby, python, php, entre outras);
			</li>
			<li>área de alunos da Fatec, oferecendo:
			</li>
				<ul>
					
					<li>
						cadastro no site, com login opcional via API do facebook
					</li>
					<li>
						gerenciamento de turma, pelos próprios alunos:
							<ul>
								<li>
									calendário de provas e trabalhos
								</li>
								<li>
									materiais adicionais para estudos
								</li>
							</ul>
					</li>
					<li>
						divulgação de atividades diversas (viagens e eventos técnicos, festas)
					</li>					
				</ul>
		</ul>	
		<li>Obter envolvimento/colaboração de alunos da Fatec.</li>
		<li>Incentivar o aprendizado e desenvolvimento com RubyOnRails entre alunos da Fatec.</li>
	</ul>	
<h3>Agradecimentos</h3>
	<p>Fontes de inspiração:</p>	
	<ul>
		<li>
			Agradecimento especial à 
			<%= link_to 'Rails Tutorial: Learn Rails by Example', 'http://ruby.railstutorial.org/ruby-on-rails-tutorial-book'%>
			, do grande <%= link_to 'Michael Hartl', 'http://www.michaelhartl.com/'%>;
		</li>

		<li>
			<%= link_to 'Ruby on Rails Brasil', 'http://rubyonrails.com.br/'%>
			e
			<%= link_to 'Ruby on Rails oficial', 'http://rubyonrails.org/'%>;
		</li>
		<li>
			<%= link_to 'StackOverFlow', 'http://stackoverflow.com/questions/tagged/ruby-on-rails'%>,
			um fórum muito útil;
		</li>
		<li>
			<%= link_to 'Fábio Akita, via AkitaOnRails', 'http://akitaonrails.com/'%>,
			se você ainda não sabe quem é, deveria saber;
		</li>
		<li>
			<%= link_to 'GoNow!', 'http://www.gonow.com.br/gonow'%>,
			porque foi uma visita com pessoal da faculdade lá que deu o empurrão
			inicial para o início deste projeto;
		</li>		
		<li>
			<%= link_to 'Blog de Erika Sarti', 'http://erikasarti.com/'%>,
			ainda preciso estudar mais as dicas que tem lá.
		</li>
		<li>
			Desculpas a todos os que não foram citados.
		</li>
		<li>
			Veja mais na página de 
				<%= link_to 'Infra-Estrutura', infraestrutura_path %>
		</li>
	</ul>
	<h4>Aviso de Responsabilidade</h4>
	<p>Nenhuma das pessoas/websites/entidades listados deram autorização para que fossem incluídos nesta página,
		e em nenhum momento endossaram ou recomendaram qualquer conteúdo publicado neste website.</p> 

app/views/videos/show.html.erb
<h1>Videos#show</h1>
<p>Find me in app/views/videos/show.html.erb</p>